# Generated by Django 3.2 on 2023-08-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('ingredients', 'name'), name='unique_recipe'),
        ),
    ]
