# Generated by Django 3.2 on 2023-08-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_unique_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipe',
        ),
    ]
